version: '3'

services:
    nginx:
        restart: always
        build: ./nginx
        container_name: nginx
        ports:
            - '80:80'
    app:
        build: ./apps
        container_name: apps
        ports:
            - '3000:3000'

    jenkins:
        build: ./jenkins
        container_name: jenkins
        volumes:
            - /var/jenkins_home
        ports:
            - '8080:8080'
            - '50000:50000'        
